orig_train_base = '/host/datasets/AIRS/trainval/train/'
train_img_dir = orig_train_base + 'image_jpg/all_classes'
train_label_dir = orig_train_base + 'label_jpg/all_classes'
train_base = '/host/DisasterDetection/datasets/AIRS/train/'
train_img_split_dir = train_base + 'image'
train_label_split_dir = train_base + 'label'
bbox_split_dir = train_base + 'bbox'
